{
  lib,
  rustPlatform,
  fetchFromGitHub,
}:
rustPlatform.buildRustPackage rec {
  pname = "form";
  version = "0.12.1";

  src = fetchFromGitHub {
    owner = "djmcgill";
    repo = "form";
    rev = "v${version}";
    hash = "sha256-aVSE6RkP/FlFQl8yeC59fY2yiFW3a7hGpijiIzHQIkE=";
  };

  cargoHash = "sha256-f1a72ZL60BsP2UOCiPSyUe/HZoKITtb9iSE0UY4lkNY=";

  meta = with lib; {
    description = "A utility to split autogenerated rust files into human-workable projects with the correct _form";
    homepage = "https://github.com/djmcgill/form";
    changelog = "https://github.com/djmcgill/form/blob/${src.rev}/CHANGELOG.md";
    license = licenses.mit;
    maintainers = with maintainers; [];
    broken = true;
    mainProgram = "form";
  };
}
