# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rime-ls = {
    pname = "rime-ls";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "wlh320";
      repo = "rime-ls";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-ZqoRFIF3ehfEeTN+ZU+/PAzA4JyS1403+sqZdzwJHA8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rime-ls-v0.4.0/Cargo.lock;
      outputHashes = {
        "librime-sys-0.1.0" = "sha256-zJShR0uaKH42RYjTfrBFLM19Jaz2r/4rNn9QIumwTfA=";
      };
    };
  };
  xdcmd = {
    pname = "xdcmd";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "TransparentLC";
      repo = "xdcmd";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-uFZbBPZYX3QQGluuyOCzs60PepPBXwgKzmDdHyxbhEc=";
    };
  };
}
