# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rime-ls = {
    pname = "rime-ls";
    version = "v0.4.3";
    src = fetchFromGitHub {
      owner = "wlh320";
      repo = "rime-ls";
      rev = "v0.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-jDn41hSDcQQO1d4G0XV6B/JZkryHtuoHUOYpmdE1Kxo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rime-ls-v0.4.3/Cargo.lock;
      outputHashes = {
        "librime-sys-0.1.0" = "sha256-RSMiuG8Jqx7DJtpzcz5Vxlc1YA2VfuawLsgUwWxKk28=";
      };
    };
  };
  xdcmd = {
    pname = "xdcmd";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "TransparentLC";
      repo = "xdcmd";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-uFZbBPZYX3QQGluuyOCzs60PepPBXwgKzmDdHyxbhEc=";
    };
  };
}
