# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rime-ls = {
    pname = "rime-ls";
    version = "v0.4.3";
    src = fetchFromGitHub {
      owner = "wlh320";
      repo = "rime-ls";
      rev = "v0.4.3";
      fetchSubmodules = false;
      sha256 = "sha256-jDn41hSDcQQO1d4G0XV6B/JZkryHtuoHUOYpmdE1Kxo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rime-ls-v0.4.3/Cargo.lock;
      outputHashes = {
        "librime-sys-0.1.0" = "sha256-RSMiuG8Jqx7DJtpzcz5Vxlc1YA2VfuawLsgUwWxKk28=";
      };
    };
  };
  uuplugin-aarch64 = {
    pname = "uuplugin-aarch64";
    version = "10.15.16";
    src = fetchurl {
      url = "https://uurouter.gdl.netease.com/uuplugin/openwrt-aarch64/v10.15.16/uu.tar.gz";
      sha256 = "sha256-rUgBGGcu5JT/w/gwIDkZA+95ODYoG7etgarDnvPsLbc=";
    };
  };
  uuplugin-x86_64 = {
    pname = "uuplugin-x86_64";
    version = "10.15.16";
    src = fetchurl {
      url = "https://uurouter.gdl.netease.com/uuplugin/openwrt-x86_64/v10.15.16/uu.tar.gz";
      sha256 = "sha256-IVXOq5kOlUl1socbBWBcLDRrY7kHlgFx6iC5krFWCVk=";
    };
  };
  xdcmd = {
    pname = "xdcmd";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "TransparentLC";
      repo = "xdcmd";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-uFZbBPZYX3QQGluuyOCzs60PepPBXwgKzmDdHyxbhEc=";
    };
  };
}
