#!/usr/bin/env just --justfile
XE_PARAMS := "-c-style-errors -interaction=nonstopmode -file-line-error -synctex=1"

test: && help
    textlive/xelatex -v
    textlive/biber -v
help:
    ## make sure to install font first
    just -l
run:make open
[no-cd]
fast-cover:
    sed -i '1s/master,pdfcover]/master]/g' scutthesis.tex
[no-cd]
cover:
    sed -i '1s/master]/master,pdfcover]/g' scutthesis.tex
[no-cd]
open:
    xdg-open scutthesis.pdf
[no-cd]
pdf: rmpdf
    textlive/xelatex {{XE_PARAMS}} scutthesis 
[no-cd]
bib:
    textlive/biber scutthesis
[no-cd]
xe:
    textlive/xelatex -no-pdf {{XE_PARAMS}} scutthesis
[no-cd]
clean:
    -rm *.aux *.lo? *.toc *.ind *.inx *.gls *.glo *.ist *.idx *.ilg *.out *.bak *.bbl *.brf *.blg *.dvi *.ps *.xdv *.run.xml *.synctex.gz *.hd *.bcf
[no-cd]
rmpdf:
    -rm scutthesis.pdf
make: clean rmpdf xe bib xe pdf
    ## run scut clean
